# Generated by Django 5.0.7 on 2024-09-14 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_product_stock_alter_product_id_alter_product_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="ProductEntry",
        ),
    ]
